// <auto-generated />
using System;
using Flashcards.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Flashcards.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlashcardsDbContext))]
    [Migration("20260930101258_AddAuthentication")]
    partial class AddAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Flashcards.Domain.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RevokedAtUtc");

                    b.ToTable("AuthSessions", (string)null);
                });

            modelBuilder.Entity("Flashcards.Domain.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Category")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExamplesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontText")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Phonetic")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("DeckId", "ArchivedAtUtc", "Id");

                    b.HasIndex("DeckId", "UpdatedAtUtc", "Id");

                    b.ToTable("Cards", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cards_ExamplesJson", "ISJSON([ExamplesJson]) = 1");
                        });
                });

            modelBuilder.Entity("Flashcards.Domain.CardReviewState", b =>
                {
                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Box")
                        .HasColumnType("int");

                    b.Property<int>("ConsecutiveSuccesses")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("LastReviewedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TotalReviews")
                        .HasColumnType("int");

                    b.Property<int>("TotalSuccesses")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("CardId");

                    b.HasIndex("DueDate", "CardId");

                    b.HasIndex("UpdatedAtUtc", "CardId");

                    b.ToTable("CardReviewStates", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReviewStates_Box", "[Box] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_ReviewStates_Counts", "[ConsecutiveSuccesses] >= 0 AND [TotalReviews] >= 0 AND [TotalSuccesses] >= 0 AND [TotalSuccesses] <= [TotalReviews] AND [ConsecutiveSuccesses] <= [TotalSuccesses]");
                        });
                });

            modelBuilder.Entity("Flashcards.Domain.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TextAlignment")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("TypographySize")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ArchivedAtUtc", "Name");

                    b.HasIndex("UserId", "UpdatedAtUtc", "Id");

                    b.ToTable("Decks", null, t =>
                        {
                            t.HasCheckConstraint("CK_Decks_TextAlignment", "[TextAlignment] IN ('ltr', 'rtl', 'center')");

                            t.HasCheckConstraint("CK_Decks_TypographySize", "[TypographySize] IN ('small', 'medium', 'large')");
                        });
                });

            modelBuilder.Entity("Flashcards.Domain.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConsumedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("AuthSessionId", "ConsumedAtUtc");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Flashcards.Domain.ReviewEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NewBox")
                        .HasColumnType("int");

                    b.Property<int>("PreviousBox")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("varchar(7)");

                    b.Property<DateTimeOffset>("ReviewedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("StudySessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CardId", "ReviewedAtUtc");

                    b.HasIndex("DeckId", "CardId");

                    b.HasIndex("DeckId", "ReviewedAtUtc");

                    b.HasIndex("UserId", "DeckId");

                    b.HasIndex("UserId", "CreatedAtUtc", "Id");

                    b.HasIndex("UserId", "ReviewedAtUtc", "Id");

                    b.ToTable("ReviewEvents", null, t =>
                        {
                            t.HasTrigger("TR_ReviewEvents_Immutable");

                            t.HasCheckConstraint("CK_ReviewEvents_Boxes", "[PreviousBox] BETWEEN 1 AND 5 AND [NewBox] BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_ReviewEvents_Result", "[Result] IN ('success', 'failure')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("Flashcards.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ArchivedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasFilter("[NormalizedEmail] IS NOT NULL");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Flashcards.Domain.UserSettings", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("DailyReminderEnabled")
                        .HasColumnType("bit");

                    b.Property<TimeOnly?>("DailyReminderTime")
                        .HasColumnType("time(0)");

                    b.Property<bool>("HapticsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("PreferredSpeechAccent")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)");

                    b.Property<string>("PreferredSpeechLanguage")
                        .IsRequired()
                        .HasMaxLength(35)
                        .IsUnicode(false)
                        .HasColumnType("varchar(35)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("UserId");

                    b.HasIndex("UpdatedAtUtc");

                    b.ToTable("UserSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserSettings_Accent", "[PreferredSpeechAccent] IS NULL OR [PreferredSpeechAccent] IN ('us', 'uk')");

                            t.HasCheckConstraint("CK_UserSettings_Reminder", "[DailyReminderEnabled] = 0 OR [DailyReminderTime] IS NOT NULL");

                            t.HasCheckConstraint("CK_UserSettings_Theme", "[Theme] IN ('system', 'light', 'dark', 'oled')");
                        });
                });

            modelBuilder.Entity("Flashcards.Domain.AuthSession", b =>
                {
                    b.HasOne("Flashcards.Domain.User", "User")
                        .WithMany("AuthSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flashcards.Domain.Card", b =>
                {
                    b.HasOne("Flashcards.Domain.Deck", "Deck")
                        .WithMany("Cards")
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("Flashcards.Domain.CardReviewState", b =>
                {
                    b.HasOne("Flashcards.Domain.Card", "Card")
                        .WithOne("ReviewState")
                        .HasForeignKey("Flashcards.Domain.CardReviewState", "CardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Card");
                });

            modelBuilder.Entity("Flashcards.Domain.Deck", b =>
                {
                    b.HasOne("Flashcards.Domain.User", "User")
                        .WithMany("Decks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flashcards.Domain.RefreshToken", b =>
                {
                    b.HasOne("Flashcards.Domain.AuthSession", "AuthSession")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AuthSessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AuthSession");
                });

            modelBuilder.Entity("Flashcards.Domain.ReviewEvent", b =>
                {
                    b.HasOne("Flashcards.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Flashcards.Domain.Card", "Card")
                        .WithMany()
                        .HasForeignKey("DeckId", "CardId")
                        .HasPrincipalKey("DeckId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Flashcards.Domain.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("UserId", "DeckId")
                        .HasPrincipalKey("UserId", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Deck");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flashcards.Domain.UserSettings", b =>
                {
                    b.HasOne("Flashcards.Domain.User", "User")
                        .WithOne("Settings")
                        .HasForeignKey("Flashcards.Domain.UserSettings", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Flashcards.Domain.AuthSession", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Flashcards.Domain.Card", b =>
                {
                    b.Navigation("ReviewState");
                });

            modelBuilder.Entity("Flashcards.Domain.Deck", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("Flashcards.Domain.User", b =>
                {
                    b.Navigation("AuthSessions");

                    b.Navigation("Decks");

                    b.Navigation("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
